### ISSUE TITLE
Increase typing coverage

### ISSUE THREAD

**Issue by ovv** [pyslackers/slack-sansio#45]

**Comment by thetonus** [comment]
Do you just want more python type annotations?

**Comment by classic-paul** [comment]
Would https://github.com/Instagram/MonkeyType be any help?

**Comment by ovv** [comment]
Hey.

> Do you just want more python type annotations?

Yes exactly, @autoferrit started adding some and it would be nice to have more.

> Would https://github.com/Instagram/MonkeyType be any help?

This look interesting. Maybe it can be useful for a quick start and then improving types where necessary.

**Comment by autoferrit** [comment]
Hmm. I realized the other day that when I had to reformat my computer, I never pushed the changes I had. Ugh. totally disappointed with myself. I had it about 75% done.

**Comment by ovv** [comment]
@autoferrit that's a shame. Do you still have your changes ? It would probably be interesting to compare what we both did

**Comment by autoferrit** [comment]
I dont. but i can look at what you did.
